/* Shared machinery for the offline test suite. Nothing in here talks to a network.

   Two facts about this repo shape everything below.

   The first is that every file in scripts/ is a top-level PROGRAM, not a module: importing
   keyframes.mjs runs it, argv and all. So logic that lives inside one of those files is reached
   by SPAWNING the script, never by importing it.

   The second is that spawning one would normally mean talking to kie.ai, and every call to
   kie.ai costs real money. So stageScript() copies the script under test - byte for byte, out of
   scripts/, at test time, so the copy can never drift from what ships - into a temp directory
   alongside a GENERATED kie.mjs. The copy's `import ... from './kie.mjs'` then resolves to the
   stub instead of the real client. The stub re-exports the genuinely pure helpers (args, state,
   confirm) from the real module, so the parser and the state loader under test are the real ones,
   and replaces every function that spends money with one that throws the word BILLABLE. A test
   that wanders onto a paid path fails loudly instead of quietly charging the card.

   That stub is also the seam a fixture-replay harness plugs into later - see test/README.md. */
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { spawnSync, execFileSync } from 'node:child_process'
import { fileURLToPath, pathToFileURL } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
export const ROOT = path.resolve(HERE, '..', '..')
export const SCRIPTS = path.join(ROOT, 'scripts')
export const KIE_URL = pathToFileURL(path.join(SCRIPTS, 'kie.mjs')).href

/* ---------- temp directories ---------- */

const made = []
process.on('exit', () => {
  for (const d of made) {
    /* maxRetries because Windows can still hold a handle on a file a child process just wrote,
       and a cleanup failure must never be what turns a green suite red. */
    try { fs.rmSync(d, { recursive: true, force: true, maxRetries: 5 }) } catch (_) {}
  }
})

export function tmpDir (label = 'ssh-test-') {
  const d = fs.mkdtempSync(path.join(os.tmpdir(), label))
  made.push(d)
  return d
}

export function write (file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, typeof contents === 'string' ? contents : JSON.stringify(contents, null, 2))
  return file
}

/* ---------- the stub kie.ai client ---------- */

/* Generated rather than checked in, because it has to be built against whatever the caller wants
   Sol to have "returned" for this one test. Everything that is not a paid call is forwarded to the
   real module: the point of the exercise is to test the real argument parser and the real state
   loader, not a second implementation of them that could agree with itself while both are wrong. */
function stubSource ({ solText = null, uploadUrl = 'https://example.invalid/uploads/fake' } = {}) {
  return `/* GENERATED by test/helpers/harness.mjs. Not part of the shipped skill. */
import fs from 'node:fs'
import { args, confirm, state } from ${JSON.stringify(KIE_URL)}
export { args, confirm, state }

const SOL_TEXT = ${JSON.stringify(solText)}
const UPLOAD_URL = ${JSON.stringify(uploadUrl)}

/* The real one reads KIE_API_KEY and exits when it is missing. The harness deliberately runs
   children with no key at all (see runScript), so this has to answer for it. */
export function requireKey () { return 'test-key-that-is-never-sent-anywhere' }

/* Free in reality, but it is still a network round trip, so it is canned like the rest. The
   shape matters: it is the {url, uploadedAt} RECORD, because passing the record where a URL
   string belongs is a defect this suite exists to keep out. */
export async function uploadFile (filePath) {
  return { url: UPLOAD_URL + '/' + encodeURIComponent(String(filePath)), uploadedAt: Date.now() }
}
export async function freshUrl (rec, filePath) { return rec || uploadFile(filePath) }

/* Records what it was called with before answering. CRITICAL-5 was a wire-shape bug - a caller
   passed uploadFile's {url, uploadedAt} RECORD where a bare URL string belongs - and no assertion
   about the storyboard's OUTPUT can see that, because the stub answers correctly either way. The
   only way to catch it is to look at the argv the caller actually built, so the stub writes it
   next to the script and test/image-url-unwrap.test.mjs reads it back. */
export async function sol (...called) {
  try { fs.writeFileSync('sol-call.json', JSON.stringify(called, null, 1)) } catch (_) {}
  if (SOL_TEXT === null) throw new Error('BILLABLE: sol() was called but this test staged no fixture')
  return SOL_TEXT
}

const billable = (name) => {
  throw new Error('BILLABLE: ' + name + '() was called. A test reached a paid code path - fix the test.')
}
export async function createTask () { billable('createTask') }
export async function pollTask () { billable('pollTask') }
export async function download () { billable('download') }
`
}

/* Copy one script into a sandbox next to the stub, and hand back the directory. */
export function stageScript (scriptName, stub = {}) {
  const dir = tmpDir('ssh-stage-')
  fs.copyFileSync(path.join(SCRIPTS, scriptName), path.join(dir, scriptName))
  fs.writeFileSync(path.join(dir, 'kie.mjs'), stubSource(stub))
  return dir
}

/* ---------- running a staged script ---------- */

/* KIE_API_KEY is stripped from the child's environment on purpose. The stub means no test should
   ever reach the real client - but if one did, the strongest possible guarantee is that there is
   no credential in scope for it to spend with. */
export function runScript (dir, scriptName, argv = [], env = {}) {
  const childEnv = { ...process.env, ...env }
  delete childEnv.KIE_API_KEY
  const r = spawnSync(process.execPath, [path.join(dir, scriptName), ...argv], {
    cwd: dir, encoding: 'utf8', env: childEnv, timeout: 120000,
  })
  const stdout = r.stdout || ''
  const stderr = r.stderr || ''
  const both = stdout + stderr
  if (/BILLABLE:/.test(both)) {
    throw new Error(`${scriptName} reached a billable call:\n${both}`)
  }
  return { status: r.status, stdout, stderr, out: both, dir }
}

/* ---------- calling an exported function that exits the process ---------- */

class Exited extends Error {}

/* args() reports every rejection with console.error + process.exit(1), which is right for a CLI
   and impossible to assert on in-process without this. Swap exit for a throw, collect the output,
   and always put both back - a leaked process.exit stub would make the whole runner unkillable. */
export function trapExit (fn) {
  const realExit = process.exit
  const realError = console.error
  const realWarn = console.warn
  const errors = []
  const warnings = []
  console.error = (...a) => errors.push(a.join(' '))
  console.warn = (...a) => warnings.push(a.join(' '))
  process.exit = (code) => { const e = new Exited(`process.exit(${code})`); e.code = code; throw e }
  try {
    const value = fn()
    return { exited: false, value, errors, warnings, text: errors.join('\n') }
  } catch (e) {
    if (e instanceof Exited) return { exited: true, code: e.code, errors, warnings, text: errors.join('\n') }
    throw e
  } finally {
    process.exit = realExit
    console.error = realError
    console.warn = realWarn
  }
}

/* ---------- capability probes ---------- */

/* The frame tests drive real ffmpeg because the thing under test is how the script reacts to the
   number of files ffmpeg actually produced; a mocked encoder would only test the mock. ffmpeg is
   a hard requirement of the skill, so this is not an optional dependency - but a contributor
   without it should get a named skip, not a red suite. */
let ffmpegCache
export function ffmpegStatus () {
  if (ffmpegCache) return ffmpegCache
  const quiet = { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }
  try {
    execFileSync('ffprobe', ['-version'], quiet)
    const encoders = execFileSync('ffmpeg', ['-hide_banner', '-encoders'], quiet)
    /* Same encoder-name-column match doctor.mjs uses, and for the same reason: the libwebp_anim
       row's description column contains the standalone token "libwebp", so a plain /\blibwebp\b/
       returns true on a build that has only the animation encoder - which cannot answer to
       `-c:v libwebp` and so cannot run the frame tests. Anchoring to the second whitespace-
       separated field of a row is what tells the two rows apart; verified against this machine's
       real listing, an anim-only listing, and one with neither. Duplicated rather than imported
       because doctor.mjs is a top-level program - importing it would run the whole preflight. */
    ffmpegCache = /^\s*\S+\s+libwebp\s/m.test(encoders)
      ? { ok: true, why: '' }
      : { ok: false, why: 'this ffmpeg has no libwebp encoder' }
  } catch (e) {
    ffmpegCache = { ok: false, why: `ffmpeg/ffprobe not on PATH (${e.code || e.message})` }
  }
  return ffmpegCache
}

export function ff (argv) {
  return execFileSync('ffmpeg', ['-v', 'error', '-y', ...argv], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
}

/* A short synthetic clip. `mp4` carries a real container duration; `h264` is a raw elementary
   stream, which ffprobe reports with NO duration at all - the case build-frames.mjs falls back to
   its recorded duration for, and the only way to drive the frame count away from --per-clip
   without hand-corrupting a file. */
export function makeClip (dest, { seconds = 1, pattern = 'testsrc', raw = false } = {}) {
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  ff(['-f', 'lavfi', '-i', `${pattern}=size=64x36:rate=25:duration=${seconds}`,
    '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p',
    ...(raw ? ['-f', 'h264'] : []), dest])
  return dest
}

/* ---------- fixtures ---------- */

/* A storyboard of the shape every downstream script expects: ids 1..n in order, n-1 motions
   chaining them. Tests deform a copy of this rather than each writing their own from scratch. */
export function storyboard (n = 4, over = {}) {
  const steps = Array.from({ length: n }, (_, i) => ({
    id: i + 1,
    label: `Stage ${i + 1}`,
    caption: `What the site looks like at stage ${i + 1}.`,
    keyframePrompt: `A photograph of the yard at stage ${i + 1}.`,
  }))
  const motions = steps.slice(0, -1).map((s, i) => ({
    from: s.id, to: steps[i + 1].id, prompt: `Work carries stage ${s.id} into stage ${s.id + 1}.`,
  }))
  return { subject: 'A bare yard becoming a finished pool', camera: 'Locked tripod, eye level', steps, motions, ...over }
}
